# Created using wingetcreate

PackageIdentifier: WingetCreateE2E.ExeTest
PackageVersion: 19.0.0
PackageLocale: en-US
Publisher: WingetCreateE2E
Author: Microsoft
PackageName: ExeTest
License: MIT
LicenseUrl: https://github.com/microsoft/winget-create
ShortDescription: Testing WingetCreate with an exe installer
Tags:
- Windows Package Manager
- winget create
- package manager
- utility
- tool
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
Installers:
- Architecture: x64
  InstallerUrl: https://fakedomain.com/ManifestCreatorTestExeInstaller.exe
  InstallerSha256: A7803233EEDB6A4B59B3024CCF9292A6FFFB94507DC998AA67C5B745D197A5DC
ManifestType: singleton
ManifestVersion: 1.0.0
